In [1]:
import numpy as np
from transformers import BertTokenizer, AutoModel
import torch
import datasets

In [3]:
model = AutoModel.from_pretrained("gpt2")

In [8]:
i = 0
for p in model.parameters():
    i+=1
i

148

In [13]:
for parameter in model.children():
    print(parameter)


Embedding(50257, 768)
Embedding(1024, 768)
Dropout(p=0.1, inplace=False)
ModuleList(
  (0-11): 12 x GPT2Block(
    (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (attn): GPT2Attention(
      (c_attn): Conv1D(nf=2304, nx=768)
      (c_proj): Conv1D(nf=768, nx=768)
      (attn_dropout): Dropout(p=0.1, inplace=False)
      (resid_dropout): Dropout(p=0.1, inplace=False)
    )
    (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (mlp): GPT2MLP(
      (c_fc): Conv1D(nf=3072, nx=768)
      (c_proj): Conv1D(nf=768, nx=3072)
      (act): NewGELUActivation()
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
)
LayerNorm((768,), eps=1e-05, elementwise_affine=True)


In [16]:
from torch import nn
lstm_layer = nn.LSTM(input_size=10, hidden_size=20, num_layers=2, batch_first=True)
# (batch_size, seq_len, input_size)
input_seq = torch.randn(3, 5, 10)
# 初始隐藏状态和细胞状态 (num_layers, batch_size, hidden_size)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output_seq, (hn, cn) = lstm_layer(input_seq, (h0, c0))
print(output_seq[0, -1]) # torch.Size([3, 5, 20])
print(hn[1, 0])         # torch.Size([2, 3, 20])

tensor([ 0.0640, -0.0756, -0.0386,  0.0328,  0.0758,  0.0314,  0.0379,  0.0301,
         0.1517, -0.0924, -0.0618,  0.1648, -0.1104, -0.0405,  0.0668,  0.0766,
         0.0952,  0.1393,  0.0134,  0.2077], grad_fn=<SelectBackward0>)
tensor([ 0.0640, -0.0756, -0.0386,  0.0328,  0.0758,  0.0314,  0.0379,  0.0301,
         0.1517, -0.0924, -0.0618,  0.1648, -0.1104, -0.0405,  0.0668,  0.0766,
         0.0952,  0.1393,  0.0134,  0.2077], grad_fn=<SelectBackward0>)


In [7]:
poem_dataloader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=8, collate_fn=dataset.collate_fn)
tokenizer = BertTokenizer.from_pretrained("uer/gpt2-chinese-cluecorpussmall")

In [3]:
t = next(iter(poem_dataloader))

In [4]:
t['token_ids'][0]

tensor([ 101, 5774, 7883, 7392, 3717, 1582, 8024, 3731, 7716, 6852, 7599, 1674,
         511, 5303, 3189, 7390, 2519,  100, 8024,  862, 3198, 5387, 7961,  100,
         511,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0])

In [9]:
''.join(tokenizer.convert_ids_to_tokens(t['token_ids'][2]))

'[CLS]欲说昭君歛翠蛾，清声委曲怨于歌。谁家年少春风里，拋与金钱唱好多。[SEP][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD][PAD]'

In [65]:
data = [str(item)[5:] for item in data]

In [67]:
np.save('data/clear_data.npy', data)

In [66]:
data[0]

'度门能不访，冒雪屡西东。已想人如玉，遥怜马似骢。乍迷金谷路，稍变上阳宫。还比相思意，纷纷正满空。'

In [64]:
tokenizer('[CLS]')

{'input_ids': [101, 101, 102], 'token_type_ids': [0, 0, 0], 'attention_mask': [1, 1, 1]}

In [60]:
data[0]

'[CLS]度门能不访，冒雪屡西东。已想人如玉，遥怜马似骢。乍迷金谷路，稍变上阳宫。还比相思意，纷纷正满空。'

100

In [55]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [56]:
tokenizer.cls_token

'[CLS]'

In [51]:
tokenizer.convert_tokens_to_ids('<|endoftext|>')

100

In [53]:
tokenizer.convert_ids_to_tokens(tokenizer('<|endoftext|>')['input_ids'])

['[CLS]', '<', '|', 'end', '##of', '##text', '|', '>', '[SEP]']